version: '3'
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    ports: 
      - ${DB_PORT}:3306

  api: 
    image: 'node:latest'
    command: > 
      bash -c "./wait-for-it.sh db:${DB_PORT} -- 
      rm -rf node_modules &&
      npm install && 
      npm start"
    environment:
      NODE_ENV: ${ENV}
      DB_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      JWT_SECRET: '${JWT_SECRET}'
    depends_on:
      - db
    volumes:
      - ./api/:/api
      - ./wait-for-it.sh/:/api/wait-for-it.sh
    working_dir: /api
    ports: 
      - 3001:3000

  client: 
    image: 'node:latest'
    command: bash -c 'rm -rf node_modules && npm install && npm run build'
    depends_on:
      - db
    volumes:
      - ./client/:/client
    working_dir: /client
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    ports:
      - "${PORT}:8080"
    volumes:
      - ./client:/srv/www/client
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - api
